root_id                        = "tf-cafes"
root_name                      = "Learn Terraform ES"
default_location               = "eastus"
deploy_corp_landing_zones      = true
deploy_online_landing_zones    = true
deploy_sap_landing_zones       = true
deploy_management_resources    = false
deploy_connectivity_resources  = false
security_contact_email_address = "security.contact@replace_me"
